### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by AustinHerman95** [AustinHerman95/fetch#1]
- [ ] Add a “fetch made” page that returns to the home activity
- [ ] Get Listener service to work, possibly a thread problem.

_Tests - Do these each time you fix something, this ensures the app's basics still work properly_
- [ ] Check boxes do what we want
- [ ] Listener listens properly given the sensitivity
- [ ] Listener handles the clap
- [ ] Vibrating method works
- [ ] Flashlight method works
- [ ] Notification method works
- [ ] Cycles through so fetches can be made constantly

**Comment by AustinHerman95** [comment]
Okay updated the list again. I fixed the ScreenLockService so it finally does what we want.
